

<div class="col-md-8 col-sm-12 col-xs-12 quitar-float center-block">

    <center><h1>Articulos Varios</h1></center>
    <center>
        <div class="botones_filtrado">
            <select id="cbx_categorias">
                <?php
                foreach ($this->categorias as $c):
                    ?>
                    <option value="<?php echo $c['categoria']; ?>"><?php echo $c['categoria']; ?></option>
                    <?php
                endforeach;
                ?>
            </select>
            <input type="button" id="btn_buscar" value="Buscar" class="btn btn-info">
        </div>
    </center>
    <div id="resultado"></div>
    <div class="row" id="productos">
        <?php
        $p = new My\Entity\Articulo();
        foreach ($this->productos as $p):
            ?>
            <div class="col-sm-6 col-md-4 col-xs-6 item">
                <div class="thumbnail">
                    <img src="<?php echo $this->baseUrl() . '/img/articulosvarios/' . $p->getUrlimagen(); ?>" class="producto">
                    <div class="caption">
                        <h3><?php echo $p->getNombre(); ?></h3>
                        <p><?php echo $p->getDescripcion(); ?> <span><?php echo $p->getPrecio(); ?></span></p>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>



<script type="text/javascript">
    $(function () {

        $("#btn_buscar").click(function () {
            var parametro = $("#cbx_categorias").val();

            actualizarTabla(parametro);

        });

        function actualizarTabla(parametro) {
            var cadenaHtml = "";
            $.ajax({
                url: 'http://localhost/perfumeriacandy/public/varios/consulta/categoria/' + parametro,
                type: 'post',
                success: function (data, textStatus, jqXHR) {
//                    $("#resultado").html('{"Producto":' + data.toString() + '}');
                    var dJson = JSON.parse('{"Producto":' + data.toString() + '}');

                    for (var i = 0; i < dJson.Producto.length; i++) {
                        cadenaHtml = cadenaHtml + '<div class="col-sm-6 col-md-4 col-xs-6 item">\n\
                                                    <div class="thumbnail">\n\
                                                        <img src="http://localhost/perfumeriacandy/public/img/articulosvarios/'+dJson.Producto[i].urlimagen+'" class="producto">\n\
                                                        <div class="caption">\n\
                                                            <h3>'+dJson.Producto[i].nombre+'</h3>\n\
                                                            <p>'+dJson.Producto[i].descripcion+'<span>'+dJson.Producto[i].precio+'</span></p>\n\
                                                        </div>\n\
                                                    </div>\n\
                                                </div>';
                    }


                    $("#productos").html(cadenaHtml);

                }
            });
        }
    });
</script>