
<div class="center-block">
    <center><h2>Perfume</h2></center>
    <div class="col-md-3 col-sm-3 col-xs-1 "></div>
    <div class="col-md-6 col-sm-6 col-xs-10 form-adm">
        <?php echo $this->form; ?>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-1 "></div>
</div>

<script>
    $(function () {
        $("#precio").removeAttr('type');
        $("#precio").attr("type", "number");
    });
</script>