<div class="col-md-8 col-sm-12 col-xs-12 quitar-float center-block">
    <center><h1 id="titulo-contacto">Contacto</h1></center>
    <div id="info-contacto">
        <?php 
        echo $this->contacto;
        ?>
        <center>
            <iframe class="thumbnail" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3356.695627445736!2d-68.59744378546722!3d-32.720714780989105!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x967e194911d428a9%3A0x8be4cc67a885fe33!2sMunicipalidad+Lavalle!5e0!3m2!1ses-419!2sar!4v1450914204139" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </center>
    </div>
</div>