<div class="center-block">
    <center><h2>Articulo</h2></center>
    <div class="col-md-3 col-sm-3 col-xs-1 "></div>
    <div class="col-md-6 col-sm-6 col-xs-10 form-adm">
        <center><h3>Imagen actual</h3><img class="thumbnail" src="<?php echo $this->baseUrl().'/img/articulosvarios/'.$this->urlimg;?>"></center>
        <?php echo $this->form; ?>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-1 "></div>
</div>