<html>
    <head>
        <meta charset="UTF-8">
        <title>Candy</title>
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/bootstrap.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/misestilos.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/administracion.css">
        <link href='https://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <section>
            <?php echo $this->layout()->content; ?>
        </section>

    </body>
</html>