

<div class="col-md-8 quitar-float center-block">

    <center><h1>Categorias de perfumes</h1></center>

    <div class="portadas-perfumes"> 
        <center>
            <a href="<?php echo $this->url(array('controller'=>'productos','action'=>'perfumes-mujer'));?>">
                <img class="img-thumbnail pose1" src="<?php echo $this->baseUrl() . '/img/perfumes/portada/portada-mujer.jpg'; ?>" class="producto">
            </a>
            <a href="<?php echo $this->url(array('controller'=>'productos','action'=>'perfumes-hombres'));?>">
                <img class="img-thumbnail pose2" src="<?php echo $this->baseUrl() . '/img/perfumes/portada/portada-hombre.jpeg'; ?>" class="producto">
            </a>
            <a href="<?php echo $this->url(array('controller'=>'productos','action'=>'perfumes-ninos'));?>">
                <img class="img-thumbnail pose3" src="<?php echo $this->baseUrl() . '/img/perfumes/portada/portada-nina.jpg'; ?>" class="producto">
            </a>
            <a href="<?php echo $this->url(array('controller'=>'productos','action'=>'perfumes-bebes'));?>">
                <img class="img-thumbnail pose4" src="<?php echo $this->baseUrl() . '/img/perfumes/portada/portada-bebe.jpg'; ?>" class="producto">
            </a>
        </center>
    </div>
</div>