

<div class="col-md-8 col-sm-12 col-xs-12 quitar-float center-block">
    
    <center><h1>Hombres</h1></center>
    
    <div class="row">
        <?php 
        $p = new My\Entity\Articulo();
        foreach ($this->perfumes as $p):?>
        <div class="col-sm-6 col-md-4 col-xs-6 item">
            <div class="thumbnail">
                <img src="<?php echo $this->baseUrl() . '/img/perfumes/'.$p->getUrlimagen(); ?>" class="producto">
                <div class="caption">
                    <h3><?php echo $p->getNombre();?></h3>
                    <p><?php echo $p->getDescripcion();?> <span><?php echo $p->getPrecio();?></span></p>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>